apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: sas-kubeconfig-pid-limit
spec:
  machineConfigPoolSelector:
    matchLabels:
      custom-kubelet: small-pods
  kubeletConfig:
    podPidsLimit: 65536