Name:         esteno-bc7r5-worker-0
Namespace:    openshift-machine-api
Labels:       machine.openshift.io/cluster-api-cluster=esteno-bc7r5
Annotations:  machine.openshift.io/memoryMb: 32768
              machine.openshift.io/vCPU: 8
API Version:  machine.openshift.io/v1beta1
Kind:         MachineSet
Metadata:
  Creation Timestamp:  2024-11-19T17:11:27Z
  Generation:          1
  Resource Version:    11287
  UID:                 882825ab-e319-470d-b14a-4339d5170643
Spec:
  Replicas:  0
  Selector:
    Match Labels:
      machine.openshift.io/cluster-api-cluster:     esteno-bc7r5
      machine.openshift.io/cluster-api-machineset:  esteno-bc7r5-worker-0
  Template:
    Metadata:
      Labels:
        machine.openshift.io/cluster-api-cluster:       esteno-bc7r5
        machine.openshift.io/cluster-api-machine-role:  worker
        machine.openshift.io/cluster-api-machine-type:  worker
        machine.openshift.io/cluster-api-machineset:    esteno-bc7r5-worker-0
    Spec:
      Lifecycle Hooks:
      Metadata:
      Provider Spec:
        Value:
          API Version:  machine.openshift.io/v1beta1
          Credentials Secret:
            Name:       vsphere-cloud-credentials
          Disk Gi B:    160
          Kind:         VSphereMachineProviderSpec
          Memory Mi B:  32768
          Metadata:
            Creation Timestamp:  <nil>
          Network:
            Devices:
              Addresses From Pools:
                Group:     installer.openshift.io
                Name:      default-0
                Resource:  IPPool
              Nameservers:
                172.23.212.216
                172.23.212.226
              Network Name:      VDS_Rede_Linux_218
          Num CP Us:             8
          Num Cores Per Socket:  4
          Snapshot:              
          Template:              esteno-bc7r5-rhcos-generated-region-generated-zone
          User Data Secret:
            Name:  worker-user-data
          Workspace:
            Datacenter:     SEFMG
            Datastore:      /SEFMG/datastore/UNITY 880XT2/VMFS_SASVAYA
            Folder:         /SEFMG/vm/Ambiente SISOP/Ambiente Analítico/Ambiente SAS Viya 4
            Resource Pool:  /SEFMG/host/ClusterAnalitico-Producao/Resources
            Server:         bhevmger01.fazenda.mg
Status:
  Observed Generation:  1
  Replicas:             0
Events:                 <none>
