apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: esteno-sas-postgres
  namespace: openshift-machine-api
spec:
  replicas: 3
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: esteno-bc7r5
      machine.openshift.io/cluster-api-machineset: esteno-sas-postgres
      machine.openshift.io/cluster-api-machine-role: worker
      machine.openshift.io/cluster-api-machine-type: worker
      machine.openshift.io/region:
      machine.openshift.io/zone:
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: esteno-bc7r5
        machine.openshift.io/cluster-api-machineset: esteno-sas-postgres
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/region:
        machine.openshift.io/zone:
    spec:
      providerSpec:
        value:
          apiVersion: machine.openshift.io/v1beta1
          kind: VSphereMachineProviderSpec
          credentialsSecret:
            name: vsphere-cloud-credentials #criar vsphere credentials secret
            namespace: openshift-machine-api
          diskGiB: 128
          memoryMiB: 32768
          numCPUs: 4
          network:
            devices:
            - addressesFromPools:
              - group: installer.openshift.io
                name: default-0
                resource: IPPool
              nameservers:
              - 172.23.212.216
              - 172.23.212.226
              networkName: VDS_Rede_Linux_218
          template: "esteno-bc7r5-rhcos-generated-region-generated-zone"
          userDataSecret:
            name: worker-user-data
          workspace:
            datacenter: "SEFMG"
            datastore: "/SEFMG/datastore/UNITY 880XT2/VMFS_SASVAYA"
            folder: "/SEFMG/vm/Ambiente SISOP/Ambiente Analítico/Ambiente SAS Viya 4"
            resourcePool: "/SEFMG/host/ClusterAnalitico-Producao/Resources"
            server: "bhevmger01.fazenda.mg"
