kind: Tuned
metadata:
  creationTimestamp: "2024-11-19T17:21:05Z"
  generation: 1
  name: kernelpidlimits
  namespace: openshift-cluster-node-tuning-operator
spec:
  profile:
  - data: |
      [main]
      summary=Optimize systems running OpenShift (provider specific parent profile)
      include=-provider-${f:exec:cat:/var/lib/ocp-tuned/provider},openshift
    name: openshift
  recommend:
  - match:
    - label: node-role.kubernetes.io/worker
    - label: sas-profile=sas-compute
    operand:
      tunedConfig: {}
    priority: 30
    profile: openshift-control-plane
  - operand:
      tunedConfig: {}
    priority: 40
    profile: openshift-node
status: {}