apiVersion: tuned.openshift.io/v1
kind: Tuned
metadata:
  creationTimestamp: "2024-12-01T19:12:37Z"
  generation: 1
  name: default
  namespace: openshift-cluster-node-tuning-operator
  resourceVersion: "7506"
  uid: c8499191-c17e-43fb-893c-fb68636f4fa3
spec:
  profile:
  - data: |
      [main]
      summary=Optimize systems running OpenShift (provider specific parent profile)
      include=-provider-${f:exec:cat:/var/lib/ocp-tuned/provider},openshift
    name: openshift
  recommend:
  - match:
    - label: node-role.kubernetes.io/master
    - label: node-role.kubernetes.io/infra
    operand:
      tunedConfig: {}
    priority: 30
    profile: openshift-control-plane
  - operand:
      tunedConfig: {}
    priority: 40
    profile: openshift-node
status: {}