apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: sas-cas
spec:
  machineConfigSelector:
    matchExpressions:
      - key: machineconfiguration.openshift.io/role
        operator: In
        values:
          - sas-cas
  nodeSelector:
    matchLabels:
      sas.profile: sas-cas
